### ISSUE TITLE
Ensure collection request bodies don't contain null values

### ISSUE THREAD

**Issue by tusharnarayan** [palantir/conjure-java#1050]
## What happened?
A request argument that is a collection type can contain `null` as a value. This leads to either `NullPointerException` (500) or requires defensive null checking.

## What did you want to happen?
Deserializing a collection value should fail with a 400/422 if any of the values in the collection are `null`. 

There shouldn't be any backwards compatibility concerns since this would only apply to request bodies that are collections.

**Comment by pkoenig10** [comment]
Related Jackson issue:
https://github.com/FasterXML/jackson-databind/issues/2734

**Comment by robert3005** [comment]
Have you tried using `--nonNullCollections` for your generated objects? It's meant to solve this exact problem

**Comment by tusharnarayan** [comment]
Per the PR that introduced that (https://github.com/palantir/conjure-java/pull/676), and through some quick testing, seems like that only handles generated objects - we also have some endpoints that consumes a collection directly, anything exist for that?

For example: `List<Foo> getFooObjects(AuthHeader authHeader, Set<ResourceIdentifier> rids)`

**Comment by iamdanfox** [comment]
@tusharnarayan are you currently using the generated undertow handlers or the jersey interfaces? In general we have far more control over the raw handlers!

**Comment by pkoenig10** [comment]
This is our internal filesystem-like service, and we are using the Undertow handlers.

Even in the Undertow handlers, we use Jackson to deserialize request bodies. So I don't think there's anything to do here unless we use custom collection types that ignore nulls or do some post-processing on the deserialized values.

**Comment by carterkozak** [comment]
When `nonNullCollections` is set, I think we can generate dialogue and undertow handlers to request a deserializer for guava `Immutable(List|Set)` which disallow null values, without modifying the exposed API to leak that implementation detail. What do you think?

**Comment by pkoenig10** [comment]
I think we can do this even if `nonNullCollections` is not set, right? As mentioned in the issue description, there shouldn't be any backwards compatibility concerns since this only applies to collections that are top-level request bodies.

I say this because it's probably not possible for us to enable `nonNullCollections` due to the backwards compatibility concerns.

**Comment by carterkozak** [comment]
I would hope that it's safe to apply when `nonNullCollections` isn't used, but we've been burned before, so I'd rather push everyone to opt into `nonNullCollections` and make it work the way we expect.

**Comment by pkoenig10** [comment]
I feel like we should provide some solution for people who can't opt in to `nonNullCollections` for backwards compatibility reasons.

This behavior is making it difficult for us to use 500s as a high signal metric, because we have a number of end users using our APIs and we can't control whether they give us null values.

The alternative is that we manually add a bunch of defensive null checks on all these endpoints, but that seems far from ideal.
