### ISSUE TITLE
Publish jar file for core Java generator code

### ISSUE THREAD

**Issue by markelliot** [palantir/conjure-java#65]
Publishing a jar for core Java generator code will allow other service targets (e.g. Undertow, Netty) to make use of the same infrastructure and type definitions while replacing the specific service outputs.

We might also consider splitting the type generators from the service generators -- but either way need things like the `TypeMapper` infrastructure to be available for services so they can refer to types.

**Comment by ferozco** [comment]
I'm hesitant to expose the internals of the generator as API. Furthermore, I think having multiple java generators would be confusing for users and should be something that we avoid. For those reasons, If there are other services generators that we want to develop we should either:
- Develop them on a branch in conjure-java
- Fork conjure-java, develop the new service generator in isolation, then merge back into conjure-java when it is more stable

**Comment by markelliot** [comment]
It doesn’t seem ideal for this project to try to aggregate all possible Java targets for Conjure, and that we ought to be thinking about the composability a bit more to avoid copying of code.

________________________________

**Comment by iamdanfox** [comment]
We've got another request for this published `:conjure-java-core` jar: @cakofony has a forked version of conjure-java that he'd like to incrementally unfork.  Having a published jar would enable them to incrementally reduce their variations while staying in sync with this codebase.

To avoid the downside of consumers trying to run the generator using java APIs which we don't consider API, I think we could publish only `:conjure-java-core` and keep the `:conjure-java` project published only as a dist (not a jar), so that people can't start directly compiling against `ConjureJavaCli`.  

Also, we could make every class in conjure-java package-private to further emphasise that we prefer people to use the published-dist API defined in [RFC002](https://github.com/palantir/conjure/blob/develop/docs/rfc/002-contract-for-conjure-generators.md)

**Comment by ferozco** [comment]
Closing in favour of PRs to add the new generators
